# Generated by Django 5.1.4 on 2025-01-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imageurl",
            options={
                "ordering": ["number"],
                "verbose_name": "Image URL",
                "verbose_name_plural": "Image URLs",
            },
        ),
        migrations.AddField(
            model_name="imageurl",
            name="number",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="Image Number"
            ),
        ),
        migrations.AlterField(
            model_name="imageurl",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Optional description for the image.",
                max_length=255,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="imageurl",
            name="offline_url",
            field=models.CharField(
                default="home img/343719885iskcon-temple.jpg",
                help_text="The path to the static offline version of the image.",
                max_length=500,
                verbose_name="Offline URL (Static)",
            ),
        ),
        migrations.AlterField(
            model_name="imageurl",
            name="online_url",
            field=models.URLField(
                default="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-C_UAhXq9GfuGO452EEzfbKnh1viQB9EDBQ&s",
                help_text="The URL for the online version of the image.",
                max_length=500,
                verbose_name="Online URL",
            ),
        ),
    ]
