# Generated by Django 3.2.25 on 2025-01-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_imageurl_options_imageurl_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='advertisements/')),
                ('order', models.PositiveIntegerField()),
                ('is_google_adsense', models.BooleanField(default=False)),
                ('position', models.CharField(choices=[('upper-menu', 'Upper menu'), ('below-menu', 'Below menu'), ('left-side-of-page', 'Left side of the page'), ('right-side-of-page', 'Right side of the page'), ('below-page', 'Below the page'), ('below-footer', 'Below footer')], default='upper-menu', max_length=50)),
                ('status', models.CharField(choices=[('enable', 'Enable'), ('disable', 'Disable')], default='enable', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ImageURL',
        ),
    ]
